# BOOKS RECOMMENDER MACHINE

### We will be building it in 4 parts 

1- Extracting and Sorting out the data


2- Popularity Based Model


3- Collaborative based filtering and finding Cosine Similarity


4- Building the Recommendation Engine 



1- Extracting and Sorting out the data- In this Step we will download the data from kaggle and then import the data from excel.the datasets containing books, users, and ratings were loaded and merged. Data cleaning techniques were applied to remove duplicates, handle missing values, and filter out inactive users and less frequently rated books. 


2- Popularity Based Model - In this step we will calculate total number of ratings and average number of ratings for each book. Books are then sorted based on these metrics to identify the most popular and highly rated books.


3- Collaborative based filtering and finding cosine similarity - In this step we created a pivot table representing the relationship between books and users. Here users who have given more than or equal to 200 ratings were seperated from the rest and books with more than or equal to 50 books  were seperated . then they both were merged and a pt file was created with pivot table. Later Cosine similarity was then calculated between books to measure how similar they are based on user rating patterns.

Cosine Similarity - So cosine similarity helps us measure how similar 2 items are based on angle between there vectors. here items=Books and vectors= user ratings for those books ratings. The values are between 0 and 1 .



4- Building the Recommendation Engine - in this step we will develop a recommendation function to suggest books similar to a given book title as the function helps the system identify identifies the most similar books using the similarity matrix and returns the top recommendations. This first step will create a function that will take book titile as input and the next step will check whether the book is present in the pivot table or not . The next function is to find the book index(rows) from the pivot table. later we create a function to find books with similarity and sort it from highest to lowest .We use [1:6] ratio to find top 5 with highest similarity. This final step integrates all previous components into a working recommendation engine capable of generating personalized suggestions.

# 1- Extracting and Sorting out the data

In [243]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [244]:
books = pd.read_csv('Books.csv.zip')
users = pd.read_csv('Users.csv.zip')
ratings = pd.read_csv('Ratings.csv.zip')

C:\Users\vishal\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [245]:
books.shape

(271360, 8)

In [316]:
books.head(4)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...

In [247]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [248]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S',]]

In [249]:
books.head(3)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...

In [250]:
users.head(4)

   User-ID                         Location   Age
0        1               nyc, new york, usa   NaN
1        2        stockton, california, usa  18.0
2        3  moscow, yukon territory, russia   NaN
3        4        porto, v.n.gaia, portugal  17.0

In [251]:
users.shape

(278858, 3)

In [252]:
ratings.head(4)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3

In [253]:
ratings.shape

(1149780, 3)

In [254]:
print (books.shape)
print (users.shape)
print (ratings.shape)

(271360, 6)
(278858, 3)
(1149780, 3)

In [255]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
dtype: int64

In [256]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [257]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [258]:
books.duplicated().sum()

0

In [259]:
ratings.duplicated().sum()

0

In [260]:
users.duplicated().sum()

0

##  2- POPULARITY BASED MODEL

In [261]:
ratings_with_name = ratings.merge (books,on='ISBN')

In [262]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...

In [263]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [264]:
num_rating_df.rename (columns={'Book-Rating': 'num_ratings'} ,inplace= True)

In [265]:
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [266]:
avg_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
avg_rating_df.rename (columns={'Book-Rating': 'avg_ratings'} ,inplace= True)

In [267]:
avg_rating_df

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [268]:
popularity_df = num_rating_df.merge(avg_rating_df, on='Book-Title')

In [269]:
popularity_df

,Book-Title,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,4
1,Always Have Popsicles,1,1
2,Apple Magic (The Collector's series),1,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,1
4,Beyond IBM: Leadership Marketing and Finance ...,1,1
...,...,...,...
241066,Ã?Â?lpiraten.,2,2
241067,Ã?Â?rger mit Produkt X. Roman.,4,4
241068,Ã?Â?sterlich leben.,1,1
241069,Ã?Â?stlich der Berge.,3,3
241070,Ã?Â?thique en toc,2,2

In [270]:
popularity_df[popularity_df ['num_ratings']>=250 ].sort_values('avg_ratings',ascending = False).head(50)

,Book-Title,num_ratings,avg_ratings
234951,Wild Animus,2502,2502
196326,The Lovely Bones: A Novel,1295,1295
183573,The Da Vinci Code,898,898
5303,A Painted House,838,838
199237,The Nanny Diaries: A Novel,828,828
27922,Bridget Jones's Diary,815,815
206502,The Secret Life of Bees,774,774
52983,Divine Secrets of the Ya-Ya Sisterhood: A Novel,740,740
204387,The Red Tent (Bestselling Backlist),723,723
14392,Angels &amp; Demons,670,670
107962,Life of Pi,664,664
162651,Snow Falling on Cedars,662,662
209298,The Summons,655,655
200253,The Notebook,650,650
210064,The Testament,617,617
85957,House of Sand and Fog,588,588
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,585
201692,The Pelican Brief,581,581
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,575
189266,The Girls' Guide to Hunting and Fishing,573,573
169201,Summer Sisters,573,573
187702,The Firm,569,569
202244,The Pilot's Wife : A Novel,568,568
80414,Harry Potter and the Chamber of Secrets (Book 2),556,556
179274,The Brethren,556,556
193428,The Joy Luck Club,555,555
219349,Timeline,552,552
6980,A Time to Kill,549,549
209117,The Street Lawyer,545,545
74750,Girl with a Pearl Earring,526,526
205523,The Runaway Jury,520,520
219741,To Kill a Mockingbird,510,510
818,1st to Die: A Novel,509,509
180737,The Chamber,509,509
93210,Interview with the Vampire,508,508
191824,The Horse Whisperer,507,507
204000,The Rainmaker,501,501
119580,Message in a Bottle,496,496
202550,The Poisonwood Bible: A Novel,494,494
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,493
76343,Good in Bed,490,490
97767,Jurassic Park,488,488
181392,The Client,483,483
55358,Dreamcatcher,481,481
201472,The Partner,478,478
159301,She's Come Undone (Oprah's Book Club),468,468
79829,Hannibal,468,468
204153,The Reader,466,466
193881,The King of Torts,458,458
170101,Suzanne's Diary for Nicholas,457,457

In [271]:
popularity_df = popularity_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','num_ratings','avg_ratings']]

In [272]:
popularity_df

,Book-Title,Book-Author,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,Karen Hesse,4,4
1,Always Have Popsicles,Rebecca Harvin,1,1
2,Apple Magic (The Collector's series),Martina Boudreau,1,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",Nancy N. Rue,1,1
4,Beyond IBM: Leadership Marketing and Finance ...,Lou Mobley,1,1
...,...,...,...,...
270291,Ã?Â?lpiraten.,Janwillem van de Wetering,2,2
270292,Ã?Â?rger mit Produkt X. Roman.,Joan Aiken,4,4
270293,Ã?Â?sterlich leben.,Anselm GrÃ?Â¼n,1,1
270294,Ã?Â?stlich der Berge.,David Guterson,3,3
270295,Ã?Â?thique en toc,Didier Daeninckx,2,2

In [273]:
popularity_df.head(50)

,Book-Title,Book-Author,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,Karen Hesse,4,4
1,Always Have Popsicles,Rebecca Harvin,1,1
2,Apple Magic (The Collector's series),Martina Boudreau,1,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",Nancy N. Rue,1,1
4,Beyond IBM: Leadership Marketing and Finance ...,Lou Mobley,1,1
5,Clifford Visita El Hospital (Clifford El Gran...,Norman Bridwell,1,1
6,Dark Justice,Jack Higgins,1,1
7,Deceived,Carla Simpson,2,2
8,Earth Prayers From around the World: 365 Pray...,Elizabeth Roberts,10,10
9,Final Fantasy Anthology: Official Strategy Gu...,David Cassady,4,4
10,Flight of Fancy: American Heiresses (Zebra Ba...,Tracy Cozzens,2,2
11,Garfield Bigger and Better (Garfield (Numbere...,Jim Davis,2,2
12,God's Little Promise Book,Word Pub,2,2
13,Good Wives: Image and Reality in the Lives of...,Laurel Thatcher Ulrich,10,10
14,Goosebumps Monster Edition 1: Welcome to Dead...,R. L. Stine,9,9
15,Harry Potter and the Bible: The Menace Behind...,Richard Abanes,1,1
16,Highland Desire (Zebra Splendor Historical Ro...,Joyce Carlow,1,1
17,Hiking the California Coastal Trail: Oregon t...,Bob Lorentzen,1,1
18,It Takes Two,Nancy Krlik,2,2
19,LA Gallinita Roja/the Little Red Hen,Lucinda McQueen,2,2
20,Little Comic Shop of Horrors (Give Yourself G...,R. L. Stine,4,4
21,Microsoft Application Architecture For Micros...,Microsoft Corporation Staff,1,1
22,Murder of a Sleeping Beauty (Scumble River My...,Denise Swanson,11,11
23,Mystery Mile,Margery Allingham,2,2
24,Nonbook Materials: The Organization of Integr...,Jean Riddle Weihs,1,1
25,Pokemon: The Official Collector's Sticker Book,Maria S. Barbo,1,1
26,"Q-Space (Star Trek The Next Generation, Book 47)",Greg Cox,17,17
27,"Q-Zone (Star Trek The Next Generation, Book 48)",Greg Cox,11,11
28,Stories of an Imaginary Childhood,Melvin Jules Bukiet,1,1
29,"Summonings: Books of Magic, Vol. 2",John Ney Rieber,2,2
30,Tales of Terror and Suspense,Allen Edgar,1,1
31,"The Secret of the Old Clock (Nancy Drew, Book 1)",Carolyn Keene,3,3
32,The Tender Commandments : Reflections on the ...,Ron Mehl,2,2
33,The Town Cats and Other Tales,Lloyd Alexander,1,1
34,This Place Has No Atmosphere (Laurel-Leaf Books),Paula Danziger,9,9
35,Tough Loser,Barthe Declements,1,1
36,Travel Companion Chile and Easter Island (Tra...,Gerry Leitner,1,1
37,Twenty Thousand Leagues Under the Sea (Illust...,Jules Verne,1,1
38,Weird News Stories,Colin Wilson,2,2
39,"Zap!: Science Fair Surprise! (Abracadabra!, B...",Peter Lerangis,1,1
40,the Devil Will Drag You Under,Jack L Chalker,1,1
41,!%@ (A Nutshell handbook),Donnalyn Frey,2,2
43,!Arriba! Comunicacion y cultura,Eduardo Zayas-Bazan,2,2
44,"!Trato hecho!: Spanish for Real Life, Combined...",John T. McMinn,1,1
45,!Yo!,Julia Alvarez,11,11
46,$14 In The Bank (Cathy Collection),Cathy Guisewite,5,5
47,$30 Film School,Michael W. Dean,1,1
48,$Weet Deal$,Brian Lysaght,1,1
49,$oft Money: The True Power in Our Nation's Cap...,E. L. Burton,5,5
50,' Allo 'Allo: the War Diaries of Rene Artois,John Haselden,1,1

## 3- COLLABORATIVE FILTERING BASED SYSTEM

In [274]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...

In [275]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating']>200

In [276]:
educated_users = x[x].index

In [277]:
educated_users

Int64Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,
              6323,   6543,
            ...
            271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427,
            277639, 278418],
           dtype='int64', name='User-ID', length=811)

In [278]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(educated_users)]

In [279]:
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...

In [280]:
filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    False
 Always Have Popsicles                                                                                        False
 Apple Magic (The Collector's series)                                                                         False
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   False
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                False
                                                                                                              ...
Ã?Â?ber das Fernsehen.                                                                                        False
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           False
Ã?Â?lpiraten.                                                                                                 False
Ã?Â?stlich der Berge.                                                                                         False
Ã?Â?thique en toc                                                                                             False
Name: Book-Rating, Length: 155845, dtype: bool

In [281]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
y[y].index

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [282]:
famous_books = y[y].index

In [283]:
filtered_rating['Book-Title'].isin(famous_books)

2          False
5          False
7          False
15         False
16         False
           ...
1030883    False
1030884    False
1030885    False
1030886    False
1030887    False
Name: Book-Title, Length: 474007, dtype: bool

In [284]:
filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...

In [285]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [286]:
final_ratings.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...

In [287]:
final_ratings.pivot_table (index='Book-Title', columns='User-ID', values='Book-Rating')

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [288]:
pt = final_ratings.pivot_table (index='Book-Title', columns='User-ID', values='Book-Rating')

In [289]:
pt.shape
pt.fillna(0,inplace=True)

In [290]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [318]:
pt.head(499)

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
The Boy Next Door,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Brethren,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Bridges of Madison County,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
The Burden of Proof,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Cardinal of the Kremlin (Jack Ryan Novels),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0

In [291]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

## Calculating Cosine Similarity

In [292]:
from sklearn.metrics.pairwise import cosine_similarity

In [293]:
cosine_similarity (pt)

array([[1.        , 0.10255025, 0.01220856, ..., 0.12110367, 0.07347567,
        0.04316046],
       [0.10255025, 1.        , 0.2364573 , ..., 0.07446129, 0.16773875,
        0.14263397],
       [0.01220856, 0.2364573 , 1.        , ..., 0.04558758, 0.04938579,
        0.10796119],
       ...,
       [0.12110367, 0.07446129, 0.04558758, ..., 1.        , 0.07085128,
        0.0196177 ],
       [0.07347567, 0.16773875, 0.04938579, ..., 0.07085128, 1.        ,
        0.10602962],
       [0.04316046, 0.14263397, 0.10796119, ..., 0.0196177 , 0.10602962,
        1.        ]])

In [294]:
cosine_similarity(pt).shape

(706, 706)

In [295]:
similarity_scores = cosine_similarity(pt)

In [296]:
similarity_scores[1]

array([0.10255025, 1.        , 0.2364573 , 0.        , 0.1095379 ,
       0.10092909, 0.11786249, 0.18761978, 0.09658879, 0.04716095,
       0.09790994, 0.07830823, 0.19121955, 0.04828673, 0.11297907,
       0.11424415, 0.11290848, 0.08432401, 0.05619509, 0.09820417,
       0.17562977, 0.05779941, 0.15727218, 0.05719732, 0.11374482,
       0.        , 0.09515326, 0.08104912, 0.02894774, 0.07225874,
       0.01714222, 0.03288122, 0.04211669, 0.09380106, 0.04486288,
       0.25375719, 0.04682287, 0.20897363, 0.05826367, 0.30746648,
       0.05386542, 0.06892792, 0.04503831, 0.074284  , 0.13507508,
       0.05023148, 0.02267079, 0.06552582, 0.05644729, 0.06294081,
       0.07553841, 0.05578722, 0.        , 0.19483247, 0.07717041,
       0.01504361, 0.10744436, 0.05396449, 0.08539351, 0.10668897,
       0.11024468, 0.        , 0.02769053, 0.23980848, 0.08922627,
       0.04639526, 0.04350087, 0.09616002, 0.1153737 , 0.01531666,
       0.13588642, 0.03504529, 0.12520455, 0.12647968, 0.10989717,
       0.1251211 , 0.08424927, 0.08526122, 0.05026875, 0.15698134,
       0.09433674, 0.07912157, 0.07627439, 0.        , 0.01589551,
       0.06294455, 0.06431867, 0.15156308, 0.05013144, 0.10249303,
       0.10971866, 0.        , 0.10874068, 0.03050783, 0.05725778,
       0.07877703, 0.19638405, 0.14909609, 0.16727162, 0.10337669,
       0.10459583, 0.08151746, 0.08099145, 0.13244984, 0.09009501,
       0.08577049, 0.1593141 , 0.10189177, 0.06271735, 0.08466493,
       0.10121841, 0.07868844, 0.08911118, 0.03912072, 0.14262589,
       0.        , 0.15121332, 0.06574573, 0.12410991, 0.13837229,
       0.11224345, 0.01789827, 0.11161535, 0.23463804, 0.        ,
       0.23511284, 0.10505007, 0.08272087, 0.09881305, 0.11947016,
       0.18879842, 0.06200539, 0.12882753, 0.03454895, 0.0732164 ,
       0.04349572, 0.03477916, 0.14061109, 0.05580235, 0.06931995,
       0.17437996, 0.06273588, 0.18685945, 0.13173708, 0.19697168,
       0.0860222 , 0.04784851, 0.05309822, 0.11713723, 0.11618649,
       0.08020742, 0.13173575, 0.12567805, 0.11011316, 0.11253827,
       0.06927818, 0.05249673, 0.06998077, 0.17630068, 0.019691  ,
       0.06299471, 0.        , 0.04131136, 0.16834334, 0.16636984,
       0.16007626, 0.13066622, 0.05953628, 0.06396094, 0.0835143 ,
       0.11061305, 0.05754624, 0.12489843, 0.04055475, 0.11036352,
       0.23637441, 0.1723661 , 0.15959235, 0.12768782, 0.03970117,
       0.12656499, 0.10153848, 0.087535  , 0.07801273, 0.04887971,
       0.07601121, 0.15863594, 0.12997598, 0.17174664, 0.1588518 ,
       0.16352905, 0.        , 0.20133968, 0.06177318, 0.21227003,
       0.05325322, 0.2458838 , 0.0791981 , 0.2104408 , 0.0256104 ,
       0.05490908, 0.        , 0.06644867, 0.19227221, 0.054237  ,
       0.17603014, 0.1415468 , 0.14237978, 0.13999595, 0.0908282 ,
       0.02743039, 0.12609024, 0.12751453, 0.08730131, 0.06429074,
       0.02272203, 0.07660775, 0.0841973 , 0.16069113, 0.02097173,
       0.10712807, 0.11368162, 0.08180118, 0.04602267, 0.15283448,
       0.11061201, 0.09866194, 0.06665448, 0.1020368 , 0.02403841,
       0.05401678, 0.02712118, 0.07628983, 0.08038818, 0.11797576,
       0.15777574, 0.1145533 , 0.        , 0.15780697, 0.13768403,
       0.11894907, 0.12464479, 0.2598933 , 0.13197444, 0.0596429 ,
       0.18953605, 0.05415311, 0.14455504, 0.        , 0.05945133,
       0.2088687 , 0.16636295, 0.02755368, 0.14660436, 0.02588857,
       0.0340486 , 0.13092248, 0.10858333, 0.143653  , 0.13469003,
       0.17132232, 0.08928005, 0.09393675, 0.09416318, 0.0425134 ,
       0.20677438, 0.0311612 , 0.14498578, 0.07473646, 0.04547424,
       0.13875263, 0.04493846, 0.11854619, 0.        , 0.08213275,
       0.12420622, 0.05279809, 0.        , 0.10765274, 0.23832918,
       0.10155095, 0.06126034, 0.01977483, 0.11680023, 0.14743377,
       0.05388142, 0.10753794, 0.09170279, 0.12466796, 0.13965493,
       0.1063607 , 0.17320896, 0.02628817, 0.22382922, 0.16630539,
       0.09771064, 0.05300349, 0.05709289, 0.06568749, 0.05005085,
       0.14531072, 0.1755074 , 0.12444585, 0.27154972, 0.07373926,
       0.09235413, 0.04472537, 0.0640034 , 0.        , 0.06287319,
       0.06729943, 0.16240974, 0.14108306, 0.13519788, 0.09344431,
       0.07128826, 0.02642704, 0.        , 0.07309867, 0.14682918,
       0.03862007, 0.13632805, 0.05764826, 0.09348958, 0.12159664,
       0.0442534 , 0.09906253, 0.        , 0.10386353, 0.11311894,
       0.09489116, 0.09767993, 0.19649142, 0.10259957, 0.04214032,
       0.11227209, 0.10451059, 0.04570411, 0.10211763, 0.06576243,
       0.0494782 , 0.15377185, 0.12086846, 0.13345557, 0.09527623,
       0.07419947, 0.05184791, 0.06542655, 0.04931013, 0.14717614,
       0.14126028, 0.04925315, 0.1204962 , 0.21727631, 0.10344644,
       0.08267066, 0.10632262, 0.13960948, 0.0377441 , 0.11664498,
       0.07821427, 0.25367009, 0.10212021, 0.10001117, 0.08903592,
       0.23132741, 0.04823949, 0.07175556, 0.04722405, 0.13786349,
       0.04011116, 0.0489358 , 0.12580649, 0.05784622, 0.11353166,
       0.03277089, 0.15190914, 0.03328972, 0.03097662, 0.06207895,
       0.0950657 , 0.09096111, 0.27803571, 0.15389615, 0.04020995,
       0.1727239 , 0.09757951, 0.10126777, 0.17436353, 0.1305113 ,
       0.04969486, 0.        , 0.10953318, 0.20455832, 0.12035901,
       0.11629737, 0.17992339, 0.04192502, 0.05263725, 0.05372548,
       0.23063474, 0.09124495, 0.08695596, 0.03033284, 0.07067235,
       0.03749226, 0.06123145, 0.28273974, 0.08833659, 0.06836809,
       0.09019429, 0.07003178, 0.08640897, 0.07513026, 0.08039066,
       0.07555192, 0.13096218, 0.08022346, 0.0796214 , 0.06975442,
       0.03622779, 0.05654447, 0.10109405, 0.03833604, 0.15808703,
       0.08128375, 0.08615018, 0.19517779, 0.08893428, 0.07796771,
       0.03443381, 0.10691045, 0.05098688, 0.04328519, 0.10144956,
       0.08412429, 0.05923732, 0.07027514, 0.19600673, 0.04812051,
       0.14123947, 0.05643584, 0.05312604, 0.05594183, 0.19402443,
       0.09210422, 0.05144376, 0.17012179, 0.11144097, 0.        ,
       0.08058097, 0.        , 0.12336465, 0.06089634, 0.13228396,
       0.01719942, 0.10537408, 0.14079955, 0.09397306, 0.10564332,
       0.0809875 , 0.05983938, 0.16223905, 0.15464884, 0.        ,
       0.04965039, 0.04710806, 0.11743094, 0.03850458, 0.        ,
       0.10361138, 0.        , 0.16393129, 0.0378243 , 0.09461635,
       0.08247602, 0.14344103, 0.        , 0.08105165, 0.06823541,
       0.10363363, 0.05923584, 0.08536802, 0.15715862, 0.04298854,
       0.        , 0.12348747, 0.1036733 , 0.08675048, 0.06256055,
       0.06617038, 0.023153  , 0.        , 0.        , 0.03987585,
       0.09328575, 0.11504961, 0.07770557, 0.07032594, 0.02667601,
       0.088408  , 0.13817124, 0.13916191, 0.03087357, 0.12383746,
       0.23059587, 0.26796288, 0.04317257, 0.12459795, 0.09196801,
       0.22440414, 0.03717709, 0.11017174, 0.08453832, 0.14991184,
       0.22208911, 0.10899709, 0.10813879, 0.13115938, 0.07123873,
       0.07548893, 0.10205291, 0.07998114, 0.12914556, 0.11877618,
       0.        , 0.25680319, 0.07477471, 0.12486312, 0.13981513,
       0.11405499, 0.09749679, 0.14868259, 0.13286288, 0.07127635,
       0.10699142, 0.10225386, 0.14315055, 0.0360085 , 0.02616267,
       0.045982  , 0.07369153, 0.05269289, 0.14051728, 0.06082863,
       0.09022351, 0.04757257, 0.00925881, 0.10959798, 0.04459178,
       0.07523306, 0.07620518, 0.15328288, 0.10768308, 0.0359473 ,
       0.03364971, 0.04201232, 0.10097695, 0.06151382, 0.12056755,
       0.08948083, 0.0803316 , 0.0990596 , 0.10475909, 0.10901812,
       0.07959552, 0.17066328, 0.04290026, 0.08316988, 0.09655001,
       0.13363793, 0.        , 0.01302815, 0.04193022, 0.07270829,
       0.145127  , 0.09173976, 0.06455346, 0.01704101, 0.10685709,
       0.03591333, 0.17219688, 0.15660571, 0.0786619 , 0.05114561,
       0.        , 0.09955718, 0.10160075, 0.16407538, 0.02960352,
       0.09813175, 0.        , 0.05172693, 0.10419871, 0.04497884,
       0.14897946, 0.11647043, 0.11374945, 0.1338449 , 0.05566729,
       0.04545451, 0.0973627 , 0.14846876, 0.06885662, 0.0381273 ,
       0.08295152, 0.09855171, 0.08961842, 0.06903189, 0.1311048 ,
       0.07887665, 0.20416822, 0.11646294, 0.10481228, 0.00387706,
       0.07438945, 0.15863695, 0.        , 0.23419137, 0.17706347,
       0.26252319, 0.09299458, 0.10772726, 0.1252514 , 0.05734607,
       0.08857531, 0.05628039, 0.11840483, 0.1826285 , 0.08880825,
       0.09084601, 0.01700102, 0.18123582, 0.06260989, 0.0551184 ,
       0.11922278, 0.10217589, 0.07860764, 0.04548456, 0.04657339,
       0.06297447, 0.09811293, 0.17817421, 0.11390134, 0.03841247,
       0.10460498, 0.21074551, 0.07563356, 0.03532216, 0.04906116,
       0.10308436, 0.09282327, 0.08562362, 0.14322812, 0.1729419 ,
       0.1443142 , 0.10690951, 0.10899005, 0.1016263 , 0.2383534 ,
       0.10288863, 0.14746625, 0.14283957, 0.09313653, 0.20204842,
       0.11011259, 0.27768096, 0.06317453, 0.07944607, 0.        ,
       0.03895899, 0.18846855, 0.15633207, 0.13548295, 0.03662368,
       0.05658947, 0.19147757, 0.14584706, 0.10316047, 0.0373302 ,
       0.12133939, 0.        , 0.15289417, 0.14152588, 0.02320639,
       0.05684525, 0.21037668, 0.06286739, 0.12345047, 0.08886457,
       0.09751591, 0.03232132, 0.07578412, 0.09254484, 0.07704462,
       0.08335279, 0.06627843, 0.07728573, 0.15254973, 0.08405529,
       0.06363305, 0.05235293, 0.19309722, 0.07446129, 0.16773875,
       0.14263397])

In [297]:
similarity_scores.shape

(706, 706)

## 4- The Recommendation Engine

In [298]:
def recommend (book_name):
    if book_name not in pt.index:
        print ("Sorry, book name does not have enough ratings to be in our system.")
        return
    #fetch index 
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted( list(enumerate(similarity_scores[index])),key=lambda x: x[1],reverse=True)[1:6]
    
    for i in similar_items:
        print(pt.index[i[0]])

In [299]:
recommend('1984')

Animal Farm
The Handmaid's Tale
Brave New World
The Vampire Lestat (Vampire Chronicles, Book II)
The Hours : A Novel

## Testing with some random books

In [300]:
recommend ('Message in a Bottle')

Nights in Rodanthe
The Mulberry Tree
A Walk to Remember
River's End
Nightmares &amp; Dreamscapes

In [301]:
books.head(57000)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...
56995,0778320448,The Shop On Blossom Street,Debbie Macomber,2004,Mira,http://images.amazon.com/images/P/0778320448.0...
56996,0809236575,1001 Ways to Save Money ... and Still Have a D...,Sharon Naylor,1994,McGraw-Hill/Contemporary Books,http://images.amazon.com/images/P/0809236575.0...
56997,0395571685,The Translator,Ward S. Just,1991,Houghton Mifflin,http://images.amazon.com/images/P/0395571685.0...
56998,1582341516,Where Do We Go from Here?,Doris Dorrie,2001,Bloomsbury Publishing (NY),http://images.amazon.com/images/P/1582341516.0...
56999,0312229461,In the Arms of Africa: The Life of Colin M. Tu...,Roy Richard Grinker,2000,St. Martin's Press,http://images.amazon.com/images/P/0312229461.0...

In [302]:
recommend ('The Translator')

Sorry, book name does not have enough ratings to be in our system.

In [303]:
pt.head(500)

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
The Brethren,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Bridges of Madison County,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
The Burden of Proof,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Cardinal of the Kremlin (Jack Ryan Novels),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0
The Carousel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0

In [304]:
recommend ('The Cardinal of the Kremlin (Jack Ryan Novels)')

Executive Orders (Jack Ryan Novels)
Patriot Games (Jack Ryan Novels)
Without Remorse
Debt of Honor (Jack Ryan Novels)
Rainbow Six

In [319]:
recommend (pt.index[498])

Executive Orders (Jack Ryan Novels)
Patriot Games (Jack Ryan Novels)
Without Remorse
Debt of Honor (Jack Ryan Novels)
Rainbow Six

### Therefore the test is sucessful and our recommendation model is ready